language: php
php: '7.1'
before_install:
  - nvm install 6
  - nvm use 6
install:
  - composer self-update
  - composer install --no-interaction
  - npm install
before_script:
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci
  - mysql -e 'create database homestead_test;'
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
script:
  - npm run production
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
services:
  - mysql
  - docker
cache:
  directories:
    - node_modules
    - vendor
